# Site settings
title: Folake Osibodu | Designer + Developer
email: folake@folakeosibodu.com
description: A portfolio of works by Folake Osibodu
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://folakeosibodu.com" # the base hostname & protocol for your site
twitter_username: fosibodu


# Build settings
markdown: kramdown
permalink: /:title
paginate: 5
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->
